spring:
 # 连接池配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 指定连接池类型
    initialSize: 5                                 # 初始化连接数
    minIdle: 5                                     # 最小连接数
    maxActive: 20                                  # 最大连接数
    maxWait: 60000                                 # 获取连接等待超时的时间
    minEvictableIdleTimeMillis: 300000             # 配置一个连接在池中最小生存的时间，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000           # 间隔多久才进行一次检测需要关闭的空闲连接，单位是毫秒
    validationQuery: SELECT 1                      # 连接池验证查询
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true                    # 是否打开PSCache
    maxPoolPreparedStatementPerConnectionSize: 20   # 指定每个连接上PSCache的大小
    filters: stat,wall,log4j                        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    #useGlobalDataSourceStat: true                  # 是否合并多个DruidDataSource的监控数据
    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
    # 自定义参数
    classpath: "classpath:mapper/*.xml"             # mapper 文件目录
    entityPackage: "com.gaoan.**.entity"           # 实体文件目录
