# 服务其他配置
spring:
  jmx:
    enabled: false
  profiles:
    active: dev        # 标志启用哪个配置文件
    
  http:
    multipart:
      max-file-size: 10MB
      location: E://Forever2//gzh_temp
  messages:
    basename: i18n/messages
    cache-seconds: 60
    fallback-to-system-locale: false
    encoding: UTF-8
  #邮件
  mail:
    form: makeys@qeveworld.com
    host: smtp.qeveworld.com
    username: makeys@qeveworld.com
    password: 026mk26+c
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
            required: false
    
# 日志管理
logging:
  config: classpath:logback-spring.xml
  path: logs
