spring:
  redis:
    port: 6379
    hostName: 127.0.0.1
    password: 654321
    database: 0     #redis数据库下标
    timeout: 2000   #超时设置
    poolConfig:
      minIdle: 1      # 最小空闲
      maxIdle: 5      # 最大空闲
      maxTotal: 500   #最大连接数